Name: gin-scaffold
Host: 0.0.0.0
Port: 8082
Mode: debug # debug release test

Log:
  StorageLocation: ./logs/
  RotationTime: 24
  RemainRotationCount: 2 #日志数量

DB:
  Driver: mysql
  DataSource: root:Aa@123456@tcp(127.0.0.1:3306)/gin-scaffold?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai

Redis:
  Host: 127.0.0.1:6379
  Pass:

