definitions:
  demo.demoCreateReq:
    properties:
      email:
        description: 邮箱
        type: string
      name:
        description: 姓名
        type: string
    required:
    - email
    - name
    type: object
  demo.demoCreateRes:
    properties:
      id:
        description: insert id
        type: string
    type: object
  demo.demoListItem:
    properties:
      avatar:
        description: 头像
        type: string
      email:
        description: 邮箱
        type: string
      id:
        description: id
        type: string
      name:
        description: 姓名
        type: string
    type: object
  demo.demoListReq:
    properties:
      page:
        description: 页码
        type: integer
      pageSize:
        description: 页大小
        type: integer
    required:
    - page
    - pageSize
    type: object
  demo.demoListRes:
    properties:
      list:
        description: 数据列表
        items:
          $ref: '#/definitions/demo.demoListItem'
        type: array
      total:
        description: 总数
        type: integer
    type: object
  demo.demoUpdateReq:
    properties:
      email:
        description: 邮箱
        type: string
      id:
        description: id
        type: string
      name:
        description: 姓名
        type: string
    required:
    - email
    - id
    - name
    type: object
  demo.demoUpdateRes:
    properties:
      id:
        description: insert id
        type: string
    type: object
  request.Resp:
    properties:
      data:
        description: 正常返回数据存放位置
      err_code:
        description: 状态码 0 success 1 failed
        type: integer
      err_msg:
        description: 错误信息描述
        type: string
    required:
    - err_code
    - err_msg
    type: object
info:
  contact: {}
paths:
  /api/v1/demo:
    get:
      consumes:
      - application/json
      description: get demo data with page
      parameters:
      - description: post params
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/demo.demoListReq'
      produces:
      - application/json
      responses:
        "200":
          description: request content
          schema:
            allOf:
            - $ref: '#/definitions/request.Resp'
            - properties:
                data:
                  allOf:
                  - $ref: '#/definitions/demo.demoListRes'
                  - properties:
                      list:
                        items:
                          $ref: '#/definitions/demo.demoListItem'
                        type: array
                    type: object
              type: object
      summary: list
      tags:
      - demo
    post:
      consumes:
      - application/json
      description: create demo data
      parameters:
      - description: post params
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/demo.demoCreateReq'
      produces:
      - application/json
      responses:
        "200":
          description: request content
          schema:
            allOf:
            - $ref: '#/definitions/request.Resp'
            - properties:
                data:
                  $ref: '#/definitions/demo.demoCreateRes'
              type: object
      summary: create
      tags:
      - demo
  /api/v1/demo/{id}:
    delete:
      consumes:
      - application/json
      description: delete demo data
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: request content
          schema:
            $ref: '#/definitions/request.Resp'
      summary: delete
      tags:
      - demo
    put:
      consumes:
      - application/json
      description: update demo data by id
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      - description: post params
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/demo.demoUpdateReq'
      produces:
      - application/json
      responses:
        "200":
          description: request content
          schema:
            allOf:
            - $ref: '#/definitions/request.Resp'
            - properties:
                data:
                  $ref: '#/definitions/demo.demoUpdateRes'
              type: object
      summary: update
      tags:
      - demo
swagger: "2.0"
